name: Update README with Icons Table

on:
  push:
    paths:
      - "Icons/**"  # Trigger on changes in the Icons folder
  workflow_dispatch:  # Allows manual runs

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Generate Icons Table and Update README
        run: |
          # Combine readmehead.md and the generated table into README.md
          python3 scripts/generate_readme.py

      - name: Commit and push changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "Auto-update README with icons"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
